# Generated by Django 5.2.3 on 2025-06-10 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Material Categories',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the material/item.', max_length=200)),
                ('sku', models.CharField(help_text='Stock Keeping Unit.', max_length=100, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_of_measure', models.CharField(help_text='e.g., pieces, meters, kg.', max_length=50)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0, help_text='Current stock quantity.')),
                ('low_quantity_threshold', models.PositiveIntegerField(default=0, help_text='Threshold for low stock warning.')),
                ('current_average_cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, help_text='Current average cost per unit of the material.', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Optional image of the item.', null=True, upload_to='material_images/')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category of the material.', on_delete=django.db.models.deletion.PROTECT, to='inventory.materialcategory')),
                ('vendor', models.ForeignKey(blank=True, help_text='Supplier of the material.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_required', models.DateField(help_text='Date when the materials are required.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the request.', max_length=10)),
                ('justification', models.TextField(blank=True, help_text='Reason for the request.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(help_text='User who made the request.', on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(help_text='Quantity of the material requested.')),
                ('fulfilled_quantity', models.PositiveIntegerField(default=0, help_text='Quantity actually fulfilled. Can be less than requested if stock is low.')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_instances', to='inventory.material')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='inventory.materialrequest')),
            ],
            options={
                'unique_together': {('material_request', 'material')},
            },
        ),
    ]
