# Generated by Django 5.2.3 on 2025-06-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_assign_group_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('IN_PROCESS', 'In Process'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', help_text='Current status of the request.', max_length=12),
        ),
    ]
