# Generated by Django 5.2.3 on 2025-06-10 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_materialrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='current_average_cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current average cost per unit. Recalculated by stock transactions.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity_on_hand',
            field=models.PositiveIntegerField(default=0, help_text='Current stock quantity. Updated by stock transactions.'),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INITIAL', 'Initial Stock'), ('RESTOCK', 'Restock')], max_length=12)),
                ('quantity_change', models.IntegerField(help_text='Quantity of material added (positive) or removed (negative, if applicable).')),
                ('cost_per_unit_at_transaction', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit for items in this specific transaction (if applicable).', max_digits=10, null=True)),
                ('total_cost_of_transaction', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of items in this transaction (quantity * cost per unit).', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions_logged', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='inventory.material')),
            ],
        ),
    ]
